generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/with-aws4
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
additionalProperties:
  withAWSV4Signature: "true"
